### ISSUE TITLE
Add tasks slide

### ISSUE THREAD

**Issue by tanyapowell** [womenhackfornonprofits/whfnp-blogging-workshop#9]
The tasks are currently 
- [x] **Split into teams** - Choose a team or 3-4 people
- [x] **Pick a topic** - A common topic that interests the team
- [x] **Blog it** - Create a draft in medium & we will hit publish soon 

@krissy @EChesters @Nandhini31 do we want to review these tasks before adding them to the slides?

**Comment by krissy** [comment]
Addressed and merged in https://github.com/womenhackfornonprofits/whfnp-blogging-workshop/issues/13
